name = "Durbyn"
uuid = "40b042de-e8ce-4d84-a20a-09ad0ba5d568"
authors = ["Resul Akay <resul.akay@taf-society.org> and contributors"]
version = "0.0.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
